### ISSUE TITLE
Missing support for non-standard squashfs v4 big endian

### ISSUE THREAD

**Issue by qkaiser** [onekey-sec/sasquatch#2]
By definition, squashfs version 4.0 is fixed little-endian. However, some implementations do not follow the standard and use big-endian. We'd like to add support for such non-standard filesystems.

A sample is available if you want, ask for `4e3fd06476376ec13c101d0362e06b6758288220`

**Comment by martonilles** [comment]
Closing as this has been fixed and a properly built sasquatch was released in https://github.com/IoT-Inspector/sasquatch/releases/tag/sasquatch-v1.0
